# Github action for publishing
# quarto documentation.

# Information on using conda environments
# for github actions can be found here:
# https://github.com/marketplace/actions/setup-miniconda

# Information on publishing quarto docs can be found here:
# https://github.com/quarto-dev/quarto-actions/tree/main

on:
  push:
    branches:
      - main

name: Render and Publish
permissions: 
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0} # Ensures you use the same shell for all commands
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4


      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 

      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions